### ISSUE TITLE
DDD설계 문의

### ISSUE THREAD

**Issue by giyeon95** [Nexters/travel-budget-server#1]
domain 분리
 - outlay (지출?)
 - plan (계획)
 - user (유저)

이렇게 3가지로 분리했는데.. 잘 분리한건지 확신이 안서서 검토후 수정사항 있을시 남겨주세요~

**Comment by godong9** [comment]
이거 어렵네요 ㅎㅎ 
저는 개인적으로 아래와 같이 생각햇었습니다.
- budget (예산)
- outlay (지출)
- plan (계획)
- user (유저)

지출하고 예산을 업데이트하는건 application 레이어에서 처리하는 느낌으로?
